version: "3"
services:
  mysql_db:
    image: atataka/mysql_db:latest
    networks:
      - server001
    ports:
      - 3306:3306
    restart: always
  node_api:
    depends_on:
      - mysql_db
    image: atataka/node_api:latest
    networks:
      - server001
    ports:
      - 3000:3000
    restart: always
networks:
  server001:
