version: "3"
services:
  mysql_db:
    image: atataka/mysql_db:latest
    networks:
      #- server001
      myNetwork:
        ipv4_address: 172.18.0.2
    ports:
      - 3306:3306
    restart: always
  node_api:
    depends_on:
      - mysql_db
    image: atataka/node_api:latest
    networks:
      #- server001
      myNetwork:
        ipv4_address: 172.18.0.5
    ports:
      - 3000:3000
    restart: always
networks:
  #server001:
  myNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1